"""Add the preset bank + WF-ratio morph + r-slider marker catalog UI to forteseq/forteseqwf.amxd.

    python tools/build_forteseqwf_presets.py            dry run, writes nothing
    python tools/build_forteseqwf_presets.py --apply    do it

forteseqwf.js already grew the engine side of this (preset bank via the Max File object,
pure-JS morph blend in startCycle(), and the four marker families generated from the
r-recursion). This script wires the Max side:

  * renames the 17 level-table toggles from the autogenerated `live.toggle[N]` to
    stable `Lvl1 On` / `Lvl1 U/C` / `Lvl1 L/R` ... names -- presets key on longname;
  * adds 6 Live parameters (Morph, Morph A, Morph B, Preset Slot, Quantize R,
    Morph R Linear) and their `prepend set*` -> js plumbing;
  * adds the non-parameter UI (marker umenu, Store/Recall/Clear buttons, three
    readout comments) in a new presentation column at x >= 420 (the device grows
    sideways only -- panel height is locked at 169);
  * adds `route ui presetslots presetname markertag` (wf_uiroute) off the js outlet,
    then a 30-token `route` demux -> `prepend set` -> each control, so recall repaints
    the visible controls without their outlets re-firing into the engine;
  * bakes the marker list (from `node forteseqwf.js --dump-markers`) into an embedded
    anonymous `coll @embed 1` and a `clear, append ...` message for the umenu.

The device is edited IN PLACE (not rebuilt from a template). Close it in BOTH Max and
Live first. See the amxd-parameter-registries note: every parameter is written to the
box `valueof` AND `patcher.parameters`; `parameterbanks` bank 0 is all "-" here so it is
left alone.
"""
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import amxd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEVICE = os.path.join(ROOT, 'forteseq', 'forteseqwf.amxd')
JS = os.path.join(ROOT, 'forteseq', 'forteseqwf.js')

PRESET_SLOTS = 20   # MUST match PRESET_SLOTS in forteseqwf.js

# --- level-table toggle renames: box id -> (longname, shortname) --------------------------
TOGGLE_RENAMES = {
    'obj-19': ('Lvl1 On', 'L1 On'),   'obj-25': ('Lvl1 U/C', 'L1 U/C'), 'obj-41': ('Lvl1 L/R', 'L1 L/R'),
    'obj-48': ('Lvl2 On', 'L2 On'),   'obj-51': ('Lvl2 U/C', 'L2 U/C'), 'obj-54': ('Lvl2 L/R', 'L2 L/R'),
    'obj-59': ('Lvl3 On', 'L3 On'),   'obj-62': ('Lvl3 U/C', 'L3 U/C'), 'obj-65': ('Lvl3 L/R', 'L3 L/R'),
    'obj-70': ('Lvl4 On', 'L4 On'),   'obj-73': ('Lvl4 U/C', 'L4 U/C'), 'obj-76': ('Lvl4 L/R', 'L4 L/R'),
    'obj-81': ('Lvl5 On', 'L5 On'),   'obj-84': ('Lvl5 U/C', 'L5 U/C'), 'obj-87': ('Lvl5 L/R', 'L5 L/R'),
    'obj-92': ('Lvl6 On', 'L6 On'),   'obj-95': ('Lvl6 U/C', 'L6 U/C'),
}

# --- token -> existing control box id, for the recall-repaint demux -----------------------
UI_TOKEN_TARGET = [
    ('r', 'obj-20'), ('m', 'obj-16'), ('n', 'obj-18'), ('period', 'obj-14'),
    ('levels', 'obj-10'), ('bpp', 'obj-78'), ('sync', 'obj-45'),
    ('on1', 'obj-19'), ('on2', 'obj-48'), ('on3', 'obj-59'), ('on4', 'obj-70'), ('on5', 'obj-81'), ('on6', 'obj-92'),
    ('uc1', 'obj-25'), ('uc2', 'obj-51'), ('uc3', 'obj-62'), ('uc4', 'obj-73'), ('uc5', 'obj-84'), ('uc6', 'obj-95'),
    ('lr1', 'obj-41'), ('lr2', 'obj-54'), ('lr3', 'obj-65'), ('lr4', 'obj-76'), ('lr5', 'obj-87'),
    ('p1', 'obj-13'), ('p2', 'obj-23'), ('p3', 'obj-44'), ('p4', 'obj-47'), ('p5', 'obj-53'), ('p6', 'obj-58'),
]

ENGINE = 'obj-6'          # js forteseqwf.js
LOADBANG = 'obj-37'
OUTPUTVALUE = 'obj-43'    # message "outputvalue" -> every toggle
SPRINTF_R = 'obj-99'      # sprintf symout %.3f  (the R readout feed)
WF_R = 'obj-20'


def dump_markers():
    """[(label, r_value), ...] in ascending r order, straight from the JS."""
    out = subprocess.check_output(['node', JS, '--dump-markers'], cwd=ROOT).decode('utf-8')
    rows = []
    for line in out.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split('\t')
        rows.append((parts[4], float(parts[1])))
    return rows


def numbox_valueof(longname, shortname, mmin, mmax, ptype, initial, modmode, unitstyle):
    return {
        'parameter_initial': [initial],
        'parameter_initial_enable': 1,
        'parameter_longname': longname,
        'parameter_mmax': mmax,
        'parameter_mmin': mmin,
        'parameter_modmode': modmode,
        'parameter_shortname': shortname,
        'parameter_type': ptype,
        'parameter_unitstyle': unitstyle,
    }


def toggle_valueof(longname, shortname):
    return {
        'parameter_enum': ['off', 'on'],
        'parameter_initial': [0],
        'parameter_initial_enable': 1,
        'parameter_longname': longname,
        'parameter_mmax': 1,
        'parameter_modmode': 0,
        'parameter_shortname': shortname,
        'parameter_type': 2,
    }


def main():
    apply_it = '--apply' in sys.argv
    markers = dump_markers()

    data, s, e, doc = amxd.load(DEVICE)
    P = doc['patcher']
    boxes = P['boxes']
    lines = P['lines']
    bx = {b['box']['id']: b['box'] for b in boxes}
    PP = P['parameters']

    n_boxes_before, n_lines_before = len(boxes), len(lines)

    nid = [max(int(i.split('-')[1]) for i in bx)]

    def fresh():
        nid[0] += 1
        return 'obj-%d' % nid[0]

    def box(**kw):
        boxes.append({'box': kw})
        return kw['id']

    def link(src, si, dst, di):
        lines.append({'patchline': {'source': [src, si], 'destination': [dst, di]}})

    # -- 1. rename the 17 level-table toggles (registry 1 + registry 2) -------------------
    for bid, (lng, shrt) in TOGGLE_RENAMES.items():
        assert bid in bx, bid
        vo = bx[bid]['saved_attribute_attributes']['valueof']
        assert vo['parameter_longname'].startswith('live.toggle'), (bid, vo['parameter_longname'])
        vo['parameter_longname'] = lng
        vo['parameter_shortname'] = shrt
        PP[bid] = [lng, shrt, 0]

    # -- 2. new Live parameters ---------------------------------------------------------
    # (varname, longname, shortname, maxclass, valueof, [pres_rect])
    P_MORPH = fresh()
    box(id=P_MORPH, maxclass='live.numbox', numinlets=1, numoutlets=2, outlettype=['', 'float'],
        parameter_enable=1, varname='wf_morph',
        annotation='Morph: 0 plays Morph A, 1 plays Morph B, in between blends the two slots '
                   '(ratio in the r-slider curve unless Morph R Linear is on). Automatable.',
        patching_rect=[1500.0, 200.0, 60.0, 15.0], presentation=1, presentation_rect=[462.0, 89.0, 166.0, 15.0],
        saved_attribute_attributes={'valueof': numbox_valueof('Morph', 'Morph', 0.0, 1.0, 0, 0.0, 3, 1)})
    P_MA = fresh()
    box(id=P_MA, maxclass='live.numbox', numinlets=1, numoutlets=2, outlettype=['', 'float'],
        parameter_enable=1, varname='wf_morpha',
        annotation='Morph A: preset slot the Morph knob starts from. 0 = the current edited state.',
        patching_rect=[1500.0, 224.0, 60.0, 15.0], presentation=1, presentation_rect=[470.0, 70.0, 30.0, 15.0],
        saved_attribute_attributes={'valueof': numbox_valueof('Morph A', 'Morph A', 0.0, float(PRESET_SLOTS), 1, 0.0, 0, 0)})
    P_MB = fresh()
    box(id=P_MB, maxclass='live.numbox', numinlets=1, numoutlets=2, outlettype=['', 'float'],
        parameter_enable=1, varname='wf_morphb',
        annotation='Morph B: preset slot the Morph knob ends at. 0 = the current edited state.',
        patching_rect=[1500.0, 248.0, 60.0, 15.0], presentation=1, presentation_rect=[518.0, 70.0, 30.0, 15.0],
        saved_attribute_attributes={'valueof': numbox_valueof('Morph B', 'Morph B', 0.0, float(PRESET_SLOTS), 1, 0.0, 0, 0)})
    P_SLOT = fresh()
    box(id=P_SLOT, maxclass='live.numbox', numinlets=1, numoutlets=2, outlettype=['', 'float'],
        parameter_enable=1, varname='wf_presetslot',
        annotation='Preset Slot: which of the %d slots Store / Recall / Clear act on.' % PRESET_SLOTS,
        patching_rect=[1500.0, 272.0, 60.0, 15.0], presentation=1, presentation_rect=[448.0, 13.0, 34.0, 15.0],
        saved_attribute_attributes={'valueof': numbox_valueof('Preset Slot', 'Slot', 1.0, float(PRESET_SLOTS), 1, 1.0, 0, 0)})
    P_QR = fresh()
    box(id=P_QR, maxclass='live.toggle', numinlets=1, numoutlets=1, outlettype=[''],
        parameter_enable=1, varname='wf_quantr',
        annotation='Quantize R: snap the R Ratio control to the nearest r-slider marker as you drag it.',
        patching_rect=[1500.0, 296.0, 15.0, 15.0], presentation=1, presentation_rect=[420.0, 146.0, 15.0, 15.0],
        saved_attribute_attributes={'valueof': toggle_valueof('Quantize R', 'Quant R')})
    P_RLIN = fresh()
    box(id=P_RLIN, maxclass='live.toggle', numinlets=1, numoutlets=1, outlettype=[''],
        parameter_enable=1, varname='wf_morphrlin',
        annotation='Morph R Linear: morph the ratio as a straight line in r instead of in the '
                   'XronoMorph r-slider curve.',
        patching_rect=[1500.0, 320.0, 15.0, 15.0], presentation=1, presentation_rect=[420.0, 108.0, 15.0, 15.0],
        saved_attribute_attributes={'valueof': toggle_valueof('Morph R Linear', 'R Lin')})

    for bid, lng, shrt in [(P_MORPH, 'Morph', 'Morph'), (P_MA, 'Morph A', 'Morph A'), (P_MB, 'Morph B', 'Morph B'),
                           (P_SLOT, 'Preset Slot', 'Slot'), (P_QR, 'Quantize R', 'Quant R'),
                           (P_RLIN, 'Morph R Linear', 'R Lin')]:
        PP[bid] = [lng, shrt, 0]

    # -- 3. prepend set* -> engine for the six new params ------------------------------
    for pid, verb in [(P_MORPH, 'setmorph'), (P_MA, 'setmorpha'), (P_MB, 'setmorphb'),
                      (P_SLOT, 'setpresetslot'), (P_QR, 'setquantizer'), (P_RLIN, 'setmorphrlinear')]:
        pp = box(id=fresh(), maxclass='newobj', numinlets=1, numoutlets=1, outlettype=[''],
                 patching_rect=[1600.0, 200.0 + 24.0 * len(lines), 150.0, 20.0], text='prepend ' + verb)
        link(pid, 0, pp, 0)
        link(pp, 0, ENGINE, 0)

    # -- 4. Store / Recall / Clear buttons --------------------------------------------
    for i, (verb, label, px) in enumerate([('storepreset', 'Store', 488.0),
                                           ('recallpreset', 'Recall', 536.0),
                                           ('clearpreset', 'Clear', 588.0)]):
        w = 44.0 if label != 'Recall' else 48.0
        btn = box(id=fresh(), maxclass='live.text', numinlets=1, numoutlets=1, outlettype=[''],
                  parameter_enable=0, mode=1, text=label, texton=label,
                  patching_rect=[1500.0, 360.0 + i * 30.0, 60.0, 20.0],
                  presentation=1, presentation_rect=[px, 12.0, w, 18.0], varname='wf_btn_' + verb[:-6])
        selb = box(id=fresh(), maxclass='newobj', numinlets=2, numoutlets=2, outlettype=['bang', ''],
                   patching_rect=[1620.0, 360.0 + i * 30.0, 40.0, 20.0], text='sel 1')
        msgb = box(id=fresh(), maxclass='message', numinlets=2, numoutlets=1, outlettype=[''],
                   patching_rect=[1680.0, 360.0 + i * 30.0, 90.0, 20.0], text=verb)
        link(btn, 0, selb, 0)
        link(selb, 0, msgb, 0)
        link(msgb, 0, ENGINE, 0)

    # -- 5. readout comments ---------------------------------------------------------
    R_NAME = box(id=fresh(), maxclass='comment', numinlets=1, numoutlets=0, text='-',
                 patching_rect=[1500.0, 460.0, 208.0, 18.0], presentation=1,
                 presentation_rect=[420.0, 33.0, 208.0, 16.0], varname='wf_presetname_readout')
    R_FILL = box(id=fresh(), maxclass='comment', numinlets=1, numoutlets=0, text='- - - - -',
                 patching_rect=[1500.0, 484.0, 208.0, 18.0], presentation=1,
                 presentation_rect=[420.0, 51.0, 208.0, 16.0], varname='wf_slotfill_readout')
    R_MRK = box(id=fresh(), maxclass='comment', numinlets=1, numoutlets=0, text='-',
                patching_rect=[1500.0, 508.0, 90.0, 18.0], presentation=1,
                presentation_rect=[492.0, 146.0, 90.0, 16.0], varname='wf_marker_readout')

    # -- 6. section + field labels (presentation only) ------------------------------
    def lbl(text, px, py, w, vn):
        box(id=fresh(), maxclass='comment', numinlets=1, numoutlets=0, text=text,
            patching_rect=[1750.0, 200.0 + 20.0 * len(boxes), max(w, 40.0), 18.0],
            presentation=1, presentation_rect=[px, py, w, 16.0], varname=vn)

    lbl('PRESETS / MORPH', 420.0, -5.0, 170.0, 'wf_lbl_presets')
    lbl('Slot', 420.0, 14.0, 26.0, 'wf_lbl_slot')
    lbl('Morph A', 420.0, 71.0, 48.0, 'wf_lbl_ma')
    lbl('B', 506.0, 71.0, 10.0, 'wf_lbl_mb')
    lbl('Morph', 420.0, 89.0, 40.0, 'wf_lbl_morph')
    lbl('R Lin', 440.0, 108.0, 40.0, 'wf_lbl_rlin')
    lbl('Marker', 420.0, 126.0, 42.0, 'wf_lbl_mrk')
    lbl('Quant R', 440.0, 146.0, 46.0, 'wf_lbl_quant')

    # -- 7. marker umenu + embedded coll + populate message -----------------------
    MENU = box(id=fresh(), maxclass='umenu', numinlets=1, numoutlets=3, outlettype=['', '', ''],
               parameter_enable=0, varname='wf_markermenu',
               patching_rect=[1500.0, 560.0, 140.0, 18.0], presentation=1,
               presentation_rect=[464.0, 125.0, 120.0, 18.0])
    coll_data = {'count': len(markers),
                 'data': [{'key': i, 'value': [r]} for i, (_lbl, r) in enumerate(markers)]}
    # @precision 17 so a Max re-save re-embeds the r-values at full double precision instead of
    # coll's default 6 significant digits (which would drift the markers vs. the JS MARKERS).
    COLL = box(id=fresh(), maxclass='newobj', numinlets=1, numoutlets=4, outlettype=['', '', '', 'bang'],
               patching_rect=[1500.0, 590.0, 160.0, 20.0], text='coll @embed 1 @precision 17',
               varname='wf_markers', coll_data=coll_data)
    MRK_R = box(id=fresh(), maxclass='newobj', numinlets=1, numoutlets=1, outlettype=[''],
                patching_rect=[1500.0, 620.0, 100.0, 20.0], text='prepend setr', varname='wf_pp_mrk_r')
    MRK_SET = box(id=fresh(), maxclass='newobj', numinlets=1, numoutlets=1, outlettype=[''],
                  patching_rect=[1620.0, 620.0, 90.0, 20.0], text='prepend set', varname='wf_pp_mrk_rset')
    items_text = 'clear, ' + ', '.join('append ' + lb for lb, _r in markers)
    MRK_ITEMS = box(id=fresh(), maxclass='message', numinlets=2, numoutlets=1, outlettype=[''],
                    patching_rect=[1500.0, 530.0, 400.0, 20.0], text=items_text, varname='wf_mrk_items')
    link(MENU, 0, COLL, 0)          # umenu LEFT outlet = chosen item number (int); middle outlet is the label symbol
    link(COLL, 0, MRK_R, 0)
    link(COLL, 0, MRK_SET, 0)
    link(COLL, 0, SPRINTF_R, 0)     # refresh the %.3f R readout
    link(MRK_R, 0, ENGINE, 0)
    link(MRK_SET, 0, WF_R, 0)
    link(LOADBANG, 0, MRK_ITEMS, 0)
    link(MRK_ITEMS, 0, MENU, 0)

    # -- 8. route ui / presetslots / presetname / markertag off the js outlet -------
    UIROUTE = box(id=fresh(), maxclass='newobj', numinlets=5, numoutlets=5, outlettype=['', '', '', '', ''],
                  patching_rect=[360.0, 300.0, 320.0, 20.0], text='route ui presetslots presetname markertag',
                  varname='wf_uiroute')
    link(ENGINE, 0, UIROUTE, 0)

    demux_tokens = [t for t, _ in UI_TOKEN_TARGET]
    DEMUX = box(id=fresh(), maxclass='newobj', numinlets=len(demux_tokens) + 1, numoutlets=len(demux_tokens) + 1,
                outlettype=[''] * (len(demux_tokens) + 1),
                patching_rect=[360.0, 340.0, 1600.0, 20.0], text='route ' + ' '.join(demux_tokens),
                varname='wf_ui_demux')
    link(UIROUTE, 0, DEMUX, 0)

    for k, (tok, target) in enumerate(UI_TOKEN_TARGET):
        pp = box(id=fresh(), maxclass='newobj', numinlets=1, numoutlets=1, outlettype=[''],
                 patching_rect=[380.0 + (k % 10) * 150.0, 380.0 + (k // 10) * 24.0, 90.0, 20.0],
                 text='prepend set', varname='wf_ppset_' + tok)
        link(DEMUX, k, pp, 0)
        link(pp, 0, target, 0)
        if tok == 'r':
            link(DEMUX, k, SPRINTF_R, 0)   # keep the %.3f readout in sync on recall too

    for oi, (vn, target) in enumerate([('wf_ppset_slotfill', R_FILL), ('wf_ppset_pname', R_NAME),
                                       ('wf_ppset_marktag', R_MRK)]):
        pp = box(id=fresh(), maxclass='newobj', numinlets=1, numoutlets=1, outlettype=[''],
                 patching_rect=[1720.0, 460.0 + oi * 24.0, 90.0, 20.0], text='prepend set', varname=vn)
        link(UIROUTE, oi + 1, pp, 0)
        link(pp, 0, target, 0)

    # -- 9. loadbang additions -----------------------------------------------------
    DEFER = box(id=fresh(), maxclass='newobj', numinlets=1, numoutlets=1, outlettype=[''],
                patching_rect=[1500.0, 660.0, 70.0, 20.0], text='deferlow', varname='wf_loadpre_defer')
    LOADMSG = box(id=fresh(), maxclass='message', numinlets=2, numoutlets=1, outlettype=[''],
                  patching_rect=[1500.0, 690.0, 90.0, 20.0], text='loadpresets', varname='wf_msg_loadpresets')
    link(LOADBANG, 0, DEFER, 0)
    link(DEFER, 0, LOADMSG, 0)
    link(LOADMSG, 0, ENGINE, 0)
    for pid in (P_MORPH, P_MA, P_MB, P_SLOT):
        link(LOADBANG, 0, pid, 0)          # bang a live.numbox -> re-emits its stored value
    link(OUTPUTVALUE, 0, P_QR, 0)          # outputvalue -> re-emit toggle state without flipping
    link(OUTPUTVALUE, 0, P_RLIN, 0)

    # ================================================================================
    # self-checks -- same class of trap check_structure.py enforces, plus registry sync
    # ================================================================================
    ids = [b['box']['id'] for b in boxes]
    assert len(ids) == len(set(ids)), 'duplicate box id'
    known = set(ids)
    idx = {b['box']['id']: b['box'] for b in boxes}
    for ln in lines:
        pl = ln['patchline']
        for lab, end in (('source', pl['source']), ('destination', pl['destination'])):
            assert isinstance(end[0], str) and end[0] in known, (lab, end)
            b = idx[end[0]]
            n = b.get('numoutlets', 0) if lab == 'source' else b.get('numinlets', 0)
            assert isinstance(end[1], int) and 0 <= end[1] < n, \
                ('%s %s idx %r out of range 0..%d on %s' % (lab, end[0], end[1], n - 1, b.get('text', b.get('maxclass'))))

    # registry 1 (box valueof longnames) must equal registry 2 (patcher.parameters), and no
    # autogenerated live.toggle[N] name may survive.
    vo_names = {}
    for b in boxes:
        bb = b['box']
        vo = (bb.get('saved_attribute_attributes') or {}).get('valueof')
        if vo and bb.get('parameter_enable'):
            vo_names[bb['id']] = vo['parameter_longname']
    pp_names = {k: v[0] for k, v in PP.items() if k not in ('parameterbanks', 'inherited_shortname')}
    assert set(vo_names) == set(pp_names), (set(vo_names) ^ set(pp_names))
    for k in vo_names:
        assert vo_names[k] == pp_names[k], (k, vo_names[k], pp_names[k])
    assert not any(str(nm).startswith('live.toggle') for nm in pp_names.values()), \
        [nm for nm in pp_names.values() if str(nm).startswith('live.toggle')]
    assert len(pp_names) == 31 + 6, len(pp_names)

    # demux consistency: token count == prepend-set boxes == demux patchlines
    demux_pp = [b for b in boxes if b['box'].get('varname', '').startswith('wf_ppset_')
                and b['box']['varname'] not in ('wf_ppset_slotfill', 'wf_ppset_pname', 'wf_ppset_marktag')]
    assert len(demux_pp) == len(UI_TOKEN_TARGET) == 30, len(demux_pp)
    demux_out_lines = [ln for ln in lines if ln['patchline']['source'][0] == DEMUX]
    assert len(demux_out_lines) == 31, len(demux_out_lines)   # 30 tokens + the extra 'r'->sprintf

    # coll rows == umenu append clauses == --dump-markers rows
    assert coll_data['count'] == items_text.count('append ') == len(markers), \
        (coll_data['count'], items_text.count('append '), len(markers))

    # every new presentation_rect sits inside the locked panel (y in [-5, 165])
    for b in boxes:
        pr = b['box'].get('presentation_rect')
        if pr and b['box']['id'] not in bx:   # only the boxes this script added
            assert pr[1] >= -5.0 and pr[1] + pr[3] <= 165.0, (b['box'].get('varname'), pr)

    assert PRESET_SLOTS == int(idx[P_MA]['saved_attribute_attributes']['valueof']['parameter_mmax'])
    assert PRESET_SLOTS == int(idx[P_MB]['saved_attribute_attributes']['valueof']['parameter_mmax'])
    assert PRESET_SLOTS == int(idx[P_SLOT]['saved_attribute_attributes']['valueof']['parameter_mmax'])

    print('forteseqwf.amxd preset/morph/markers build')
    print('  markers      : %d  (%s .. %s)' % (len(markers), markers[0][0], markers[-1][0]))
    print('  boxes        : %d -> %d  (+%d)' % (n_boxes_before, len(boxes), len(boxes) - n_boxes_before))
    print('  lines        : %d -> %d  (+%d)' % (n_lines_before, len(lines), len(lines) - n_lines_before))
    print('  params       : %d  (renamed 17 toggles, added 6)' % len(pp_names))
    print('  new param ids : %s' % ', '.join([P_MORPH, P_MA, P_MB, P_SLOT, P_QR, P_RLIN]))

    if not apply_it:
        print('')
        print('(dry run -- nothing written; re-run with --apply)')
        return

    shutil.copyfile(DEVICE, DEVICE + '.before')
    print('  backup       : %s.before' % os.path.basename(DEVICE))
    amxd.save(DEVICE, data, s, e, doc)

    d2, s2, e2, doc2 = amxd.load(DEVICE)
    P2 = doc2['patcher']
    assert len(P2['boxes']) == len(boxes), (len(P2['boxes']), len(boxes))
    assert len(P2['lines']) == len(lines)
    back_pp = {k: v[0] for k, v in P2['parameters'].items()
              if k not in ('parameterbanks', 'inherited_shortname')}
    assert set(back_pp.values()) == set(pp_names.values()), set(back_pp.values()) ^ set(pp_names.values())
    print('')
    print('wrote %s' % DEVICE)
    print('now: python tools/check_structure.py forteseq/forteseqwf.amxd')


main()
